services:
  - type: web
    name: athena-library
    runtime: node
    buildCommand: npm install && npm install --prefix client && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
